# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_stages:
  - commit
repos:
  # General
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: [ '--maxkb=1000' ]
      - id: pretty-format-json
        args: [ --autofix, --indent, "2" ]
        exclude: /package-lock\.json$
      - id: no-commit-to-branch
        args: [ "--branch", "main" ]

  # Secrets
  - repo: https://github.com/awslabs/git-secrets
    rev: 99d01d5
    hooks:
      - id: git-secrets

  # CloudFormation
  - repo: https://github.com/aws-cloudformation/cfn-python-lint
    rev: v0.70.1
    hooks:
      - id: cfn-python-lint
        name: AWS CloudFormation Linter
        files: template.yaml$
        args: [ --ignore-checks=W2001, --ignore-checks=W3002, --ignore-checks=W3011 ]

  # JS
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1"
    hooks:
      - id: prettier
        name: Prettier
        files: \.(js)
