AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Events Service - Amazon API Gateway to AWS Lambda to Amazon DynamoDB to store event from events producers

Globals:

  Function:
    Runtime: python3.11
    Tracing: Active
    Layers:
      - !Sub arn:aws:lambda:${AWS::Region}:017000801446:layer:AWSLambdaPowertoolsPythonV2:32
    Environment:
      Variables:
        POWERTOOLS_SERVICE_NAME: events

Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Description: 'Lambda function that inserts data into DynamoDB table'
    Properties:
      FunctionName:
      Handler: app.lambda_handler
      CodeUri: ../lambda/events/receiver/
      Description: Lambda for receiving betting events
      Runtime: python3.11
      Timeout: 10
      MemorySize: 256
      Policies:
        DynamoDBCrudPolicy:
          TableName: !Ref DynamoDBTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: POST
  DynamoDBTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: BettingEvents
Outputs:
  EndpointUrl:
    Description: 'HTTP REST endpoint URL'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod'
