AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Sporting Events Service - Amazon API Gateway to AWS Lambda to process and store sporting events from events producers
Globals:

  Function:
    Runtime: python3.9
    Tracing: Active
    Layers:
      - !Sub arn:aws:lambda:${AWS::Region}:017000801446:layer:AWSLambdaPowertoolsPythonV2:32
    Environment:
      Variables:
        POWERTOOLS_SERVICE_NAME: sportingevents

Parameters:
  EventBus:
    Type: String

Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Description: 'Lambda function that receives data from event producers and processes them'
    Properties:
      FunctionName:
      Handler: app.lambda_handler
      CodeUri: ../lambda/sportingevents/receiver/
      Description: Lambda for receiving sporting events
      Runtime: python3.9
      Timeout: 10
      MemorySize: 256
      Policies:
        - EventBridgePutEventsPolicy:
            EventBusName: !Ref EventBus
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: POST
      Environment:
        Variables:
          EVENT_BUS: !Ref EventBus

Outputs:
  EndpointUrl:
    Description: 'HTTP REST endpoint URL'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod'