AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Globals:

  Function:
    Runtime: python3.12
    Tracing: Active
    Layers:
      - !Sub arn:aws:lambda:${AWS::Region}:017000801446:layer:AWSLambdaPowertoolsPythonV3-python312-x86_64:10
    Environment:
      Variables:
        POWERTOOLS_SERVICE_NAME: trading

Parameters:

  EventBus:
    Type: String
  
  LambdaEnvKmsKeyArn:
    Type: String
    Default: ""
    Description: ARN of the KMS key for Lambda environment variable encryption

Resources:

  SQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 60
      SqsManagedSseEnabled: true
      RedrivePolicy:
        maxReceiveCount: 2
        deadLetterTargetArn: !GetAtt DLQ.Arn

  DLQ:
    Type: AWS::SQS::Queue
    Properties:
      SqsManagedSseEnabled: true

  EventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "TradingThirdParty"
      EventBusName: !Ref EventBus
      EventPattern:
        source:
          - "com.thirdparty"
      Targets:
        - Arn: !GetAtt SQSQueue.Arn
          Id: SQSqueue

  EventBridgeToToSqsPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: events.amazonaws.com
          Action: sqs:SendMessage
          Resource:  !GetAtt SQSQueue.Arn
          Condition:
            StringEqualsIfExists:
              aws:SourceAccount: !Ref AWS::AccountId
            Bool:
              aws:SecureTransport: "true"
      Queues:
        - Ref: SQSQueue

  TradingBatchFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      CodeUri: ../lambda/trading/receiver/
      Description: Lambda for receiving events from the trading queue
      Timeout: 10
      MemorySize: 256
      KmsKeyArn: !Ref LambdaEnvKmsKeyArn
      Environment:
        Variables:
          EVENT_BUS: !Ref EventBus
      Policies:
        - EventBridgePutEventsPolicy:
            EventBusName: !Ref EventBus
        - Statement:
            - Effect: Allow
              Action:
                - kms:Decrypt
                - kms:DescribeKey
              Resource: !Ref LambdaEnvKmsKeyArn
      DeadLetterQueue:
        Type: SQS  # Can be SQS or SNS
        TargetArn: !GetAtt DLQ.Arn
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt SQSQueue.Arn
            BatchSize: 10
            FunctionResponseTypes:
              - ReportBatchItemFailures

Outputs:
  QueueName:
    Description: SNS queue name
    Value: !GetAtt SQSQueue.QueueName

  QueueARN:
    Description: SQS queue ARN
    Value: !GetAtt SQSQueue.Arn

  QueueURL:
    Description: SQS queue URL
    Value: !Ref SQSQueue
